server:
  port: 7002

eureka:
  instance:
    hostname: eureak7002.com
  client:
    register-with-eureka: false #false表示不向服务注册中心注册自己
    fetch-registry: false #false表示自己端就是注册中心
    service-url:
      defaultZone: http://eureka7001.com:7001/erueka #检索7001的服务
  server:
    #关闭自我保护机制，保证不可用服务被及时踢除
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 2000



